#!/usr/bin/env bash

script_path=${0%/*}
if [[ ! -d "$script_path" ]]; then script_path="$PWD"; fi
. "$script_path/parse_podify_args"
. "$script_path/podified_utils"

add_service_accounts_to_anyuid_scc() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 2 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  project_name="$1"
  release="$2"

  echo -e "\n  # Add the ${release}-anyuid and ${release}-orchestrator service accounts to the anyuid Security Context Constraints (SCC)"
  run_cmd "oc adm policy add-scc-to-user anyuid system:serviceaccount:${project_name}:${release}-anyuid"
  run_cmd "oc adm policy add-scc-to-user anyuid system:serviceaccount:${project_name}:${release}-orchestrator"
  run_cmd "oc describe scc anyuid | grep Users"
}

add_privileged_service_accounts_to_privileged_scc() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 2 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  project_name="$1"
  release="$2"

  echo -e "\n  # Add the ${release}-privileged service account to the privileged Security Context Constraints (SCC)"
  run_cmd "oc adm policy add-scc-to-user privileged system:serviceaccount:${project_name}:${release}-privileged"
  run_cmd "oc describe scc privileged | grep Users"
}

setup_the_httpd_service_account() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 3 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  project_name="$1"
  release="$2"
  templates="$3"

  echo -e "\n  # Create the ${release}-sysadmin SCC and add the ${release}-httpd service account to it."

  if [[ $minishift == true ]]; then
    run_cmd "oc create -f ${templates}/${release}-scc-sysadmin.yaml"
    scc="${release}-sysadmin"
  else
    scc="anyuid"
  fi

  run_cmd "oc adm policy add-scc-to-user ${scc} system:serviceaccount:${project_name}:${release}-httpd"
  run_cmd "oc describe scc ${scc} | grep Users"
}

create_db_pv() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 1 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  project_name="$1"

  if [[ $minishift == true ]]; then
    echo -e "\n  # Make a persistent volume to host the database data"

    # JJV TBD
  fi
}

deploy_mgr() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 3 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  template_name="$1"
  release="$2"
  templates="$3"

  echo -e "\n  # Create the template for deployment and verify it is now available in your project"
  run_cmd "oc create -f ${templates}/${release}-template.yaml"
  run_cmd "oc new-app --template=${template_name}"
}

parse_podify_args "$@"
set_release_context "${release}" "manageiq-pods" "${repo}" "${branch}"
oc_logout
oc_login "${openshift_host}" "${openshift_port}" "${openshift_user}"
new_project "${project_name}" "${project_description}" "${project_displayname}"
set_project "${project_name}"
add_service_accounts_to_anyuid_scc "${project_name}" "${release}"
add_privileged_service_accounts_to_privileged_scc "${project_name}" "${release}"
setup_the_httpd_service_account "${project_name}" "${release}" "${templates}"
create_db_pv "${project_name}"
deploy_mgr "${template_name}" "${release}" "${templates}" 
