#!/usr/bin/env bash

script_path=${0%/*}
if [[ ! -d "$script_path" ]]; then script_path="$PWD"; fi
. "$script_path/parse_podify_args"
. "$script_path/podified_utils"

setup_the_httpd-cmg_service_account() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 2 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  project_name="$1"
  templates="$2"

  echo -e "\n  # Create the httpd-scc-sysadmin SCC"
  run_cmd "oc create -f ${templates}/httpd-scc-sysadmin.yaml"

  echo -e "\n  # Include the httpd-configmap-generator service account with the new SCC"
  run_cmd "oc adm policy add-scc-to-user httpd-scc-sysadmin system:serviceaccount:${project_name}:httpd-configmap-generator"
  run_cmd "oc describe scc httpd-scc-sysadmin | grep Users"
}

adjust_templates() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 1 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  templates="$1"

  old="manageiq-pods"
  new="httpd_configmap_generator"

  echo -e "\n  ${templates}"
  echo -e "\n  # Update replace ${old} with ${new} in the templates URL"
  templates="${templates/$old/$new}"

  echo -e "\n  ${templates}"

}
  
deploy_cmg() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 1 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  templates="$1"

  echo -e "\n  # Deploy the Httpd Configmap Generator Application"

  run_cmd "oc create -f ${templates}/httpd-configmap-generator-template.yaml"
  run_cmd "oc new-app --template=httpd-configmap-generator"
}
  
parse_podify_args "$@"
adjust_templates "${templates}"
oc_logout
oc_login "${openshift_host}" "${openshift_port}" "${openshift_user}"
new_project "${project_name}" "${project_description}" "${project_displayname}"
set_project "${project_name}"
setup_the_httpd-cmg_service_account "${project_name}" "${templates}"
deploy_cmg "${templates}"
