#!/usr/bin/env bash

script_path=${0%/*}
if [[ ! -d "$script_path" ]]; then script_path="$PWD"; fi
. "$script_path/parse_podify_args"
. "$script_path/podified_utils"

scale_down_dcs() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  echo -e "\n  # Scale all deploymentconfigs to 0"
  for i in $(run_cmd "oc get dc -o name" | cut -d '/' -f 2 | grep -v "  oc"); do
    run_cmd "oc scale dc $i --replicas=0"
  done
}

scale_down_statefulset() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  echo -e "\n  # Scale all statefulset to 0"
  for i in $(run_cmd "oc get statefulsets -o name" | cut -d '/' -f 2 | grep -v "  oc"); do
    run_cmd "oc scale statefulsets $i --replicas=0"
  done
}

wait_for_pod_scale_down() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  echo -e "\n  # wait for all pods to scale to 0"
  while [[ $( run_cmd "oc get pods" | grep -v "Error" | grep -v "oc get pods" | wc -l ) -ne 0 ]]; do
    echo "Pods still running"
    sleep 10
  done
  echo "Done"

}

delete_application() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 1 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  template_name="$1"

  echo -e "\n  # Delete the application"
  run_cmd "oc delete all -l app=${template_name}"
}

delete_project() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  if [[ $# -ne 1 ]]; then
    error_exit "${FUNCNAME} invoked with wrong number of arguments"
  fi
  project_name="$1"

  echo -e "\n  # Delete the project"
  run_cmd "oc delete project ${project_name}"
}

parse_podify_args "$@"
set_release_context "${release}" "manageiq-pods" "${repo}" "${branch}"
oc_logout
oc_login "${openshift_host}" "${openshift_port}" "${openshift_user}"
set_project "${project_name}"
scale_down_dcs
scale_down_statefulset
wait_for_pod_scale_down
delete_application "${template_name}"
delete_project "${project_name}"

