#!/usr/bin/env bash
script_path=${0%/*}
if [[ ! -d "$script_path" ]]; then script_path="$PWD"; fi
. "$script_path/parse_cmg_args"
. "$script_path/podified_utils"
. "$script_path/cmd_line_utils"

set_cmg_pod() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  cmg_pod=`cmg_pod`
  if [[ -z "$cmg_pod" ]]; then
    error_exit "${FUNCNAME} Configmap Generator Pod is not running"
  fi

  echo -e "\n  # Configmap Generator Pod: ${cmg_pod}"
}

generate_configmap() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  # Devel: cmg_cmd="/opt/httpd_configmap_generator/bin/httpd_configmap_generator"
  cmg_cmd="httpd_configmap_generator"
  echo -e "\n  # Invoking $cmg_cmd ipa on $cmg_pod ..."

  long_cmd="oc exec $cmg_pod -- bash -c '$cmg_cmd ipa "
  long_cmd+="--force "
  long_cmd+="--host=${mgr_host} "
  long_cmd+="--ipa-server=${server} "
  long_cmd+="--ipa-domain=${domain} "
  long_cmd+="--ipa-realm=${realm} "
  long_cmd+="--ipa-principal=${principal_user} "
  long_cmd+="--ipa-password=${principal_user_password} "
  long_cmd+="--debug "
  long_cmd+="-o /tmp/external-ipa.yaml '"

  run_cmd "${long_cmd}"
  if [[ $run_cmd_status -ne 0 ]]; then
    error_exit "${FUNCNAME} Failed to generate the config map"
  fi
}

fecth_configmap() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  echo -e "\n  # Fetching external-ipa.yaml"
  run_cmd "oc cp $cmg_pod:/tmp/external-ipa.yaml ./external-ipa.yaml"
  if [[ $run_cmd_status -ne 0 ]]; then
    error_exit "${FUNCNAME} Failed to fetch the new config map"
  fi
}

parse_cmg_args "$@"
set_cmg_pod
generate_configmap
fecth_configmap

# JJV scale_down_cmg

