#!/usr/bin/env bash

usage() {
  this_script="$(basename $0)"

  # Optional
  echo "Usage: ${this_script} [options]"

  echo "Required options:"
  echo "  -h <OpenShift Host> \\"
  echo "  -p <OpenShift Port> \\"
  echo "  -u <OpenShift User> \\"
  echo "  -P <Project Name> \\"
  echo ""

  echo "Optional options:"
  echo "  -t                        [false]    trial_run flag \\"
  echo "  -m                        [false]    minishift flag \\"
  echo "  -N                        [manageiq] cloudforms || manageiq \\"
  echo "  -T <templet URL>          [https://raw.githubusercontent.com/ManageIQ/manageiq-pods/master/templates] \\"
  echo "  -d <Project Description>  [none] \\"
  echo "  -D <Project Display>      [none] \\"
  echo "  -a <application domain>   [none] \\"
  echo ""

  echo "Example usage:"
  echo "${this_script} \\"
  echo "  -h openshift.example.com \\"
  echo "  -p 8443 \\"
  echo "  -u bob \\"
  echo "  -P my-project \\"
  echo "  -d \"My Project Example\" \\"
  echo "  -D \"My Project\""
  echo ""
}

parse_podify_args() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  application_domain=""
  minishift=false
  project_description=""
  project_displayname=""
  template_name="manageiq"
  template_prefix="miq"
  templates="https://raw.githubusercontent.com/ManageIQ/manageiq-pods/master/templates"
  trial_run=false

  while getopts "h:p:u:P:d:D:a:tN:T:m" opt; do
    case $opt in
    h)
      openshift_host=$OPTARG
      ;;
    p)
      openshift_port=$OPTARG
      ;;
    u)
      openshift_user=$OPTARG
      ;;
    P)
      project_name=$OPTARG
      ;;
    d)
      project_description=$OPTARG
      ;;
    D)
      project_displayname=$OPTARG
      ;;
    a)
      application_domain=$OPTARG
      ;;
    t)
      trial_run=true
      ;;
    N)
      template_name=$OPTARG
      ;;
    T)
      templates=$OPTARG
      ;;
    m)
      minishift=true
      ;;
    ?)
      echo "*** ? ***"
      usage
      exit 1
      ;;
    :)
      echo "*** : ***"
      usage
      exit 1
      ;;
    esac
  done

  if [[ -z $openshift_host ]]; then
    echo "Missing *REQUIRED* field:"
    echo "  -h <OpenShift Host> *REQUIRED* Openshift Host Name \\"
    echo ""
    usage
    exit 1
  fi

  if [[ -z $openshift_port ]]; then
    echo "Missing *REQUIRED* field:"
    echo "  -p <OpenShift Port> *REQUIRED* Openshift Port Number \\"
    echo ""
    usage
    exit 1
  fi

  if [[ -z $openshift_user ]]; then
    echo "Missing *REQUIRED* field:"
    echo "  -u <OpenShift User> *REQUIRED* Openshift User Name \\"
    echo ""
    usage
    exit 1
  fi

  if [[ -z $project_name ]]; then
    echo "Missing *REQUIRED* field:"
    echo "  -P <Project Name>   *REQUIRED* Openshift Project Name \\"
    echo ""
    usage
    exit 1
  fi

  if [[ $template_name != "cloudforms" ]] && [[ $template_name != "manageiq" ]]; then
    echo "Invalied value:"
    echo "  -N <template name> must be manageiq or cloudforms \\"
    echo ""
    usage
    exit 1
  fi

  if [[ $template_name == "cloudforms" ]]; then
    template_prefix="cfme"
  fi

  echo "openshift_host       ->${openshift_host}<-"
  echo "openshift_port       ->${openshift_port}<-"
  echo "openshift_user       ->${openshift_user}<-"
  echo "project_name         ->${project_name}<-"
  echo "project_description  ->${project_description}<-"
  echo "project_displayname  ->${project_displayname}<-"
  echo "application_domain   ->${application_domain}<-"
  echo "template_name        ->${template_name}<-"
  echo "template_prefix      ->${template_prefix}<-"
  echo "templates            ->${template}<-"
  echo "minishift            ->${minishift}<-"
  echo "trial_run            ->${trial_run}<-"
}

