#!/usr/bin/env bash

usage() {
  this_script="$(basename $0)"

  # Optional
  echo "Usage: ${this_script} [options]"

  echo "Required options:"
  echo "  -h <OpenShift Host> \\"
  echo "  -p <OpenShift Port> \\"
  echo "  -u <OpenShift User> \\"
  echo "  -P <Project Name> \\"
  echo ""

  echo "Optional options:"
  echo "  -t                        [false]    trial_run flag \\"
  echo "  -R                        [manageiq] cloudforms || manageiq \\"
  echo "  -m                        [false]    minishift flag \\"
  echo "  -r <git repo>             [ManageIQ] \\"
  echo "  -b <git branch>           [master] \\"
  echo "  -d <Project Description>  [none] \\"
  echo "  -D <Project Display>      [none] \\"
  echo "  -a <application domain>   [none] \\"
  echo ""

  echo "Example usage:"
  echo "${this_script} \\"
  echo "  -h openshift.example.com \\"
  echo "  -p 8443 \\"
  echo "  -u bob \\"
  echo "  -P my-project \\"
  echo "  -d \"My Project Example\" \\"
  echo "  -D \"My Project\""
  echo ""
}

parse_podify_args() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  application_domain=""
  branch="master"
  minishift=false
  project_description=""
  project_displayname=""
  release="miq"
  repo="ManageIQ"
  trial_run=false

  while getopts "h:p:u:P:d:D:a:tR:mr:b:" opt; do
    case $opt in
    h)
      openshift_host=$OPTARG
      ;;
    p)
      openshift_port=$OPTARG
      ;;
    u)
      openshift_user=$OPTARG
      ;;
    P)
      project_name=$OPTARG
      ;;
    d)
      project_description=$OPTARG
      ;;
    D)
      project_displayname=$OPTARG
      ;;
    a)
      application_domain=$OPTARG
      ;;
    t)
      trial_run=true
      ;;
    R)
      release=$OPTARG
      ;;
    m)
      minishift=true
      ;;
    r)
      repo=$OPTARG
      ;;
    b)
      branch=$OPTARG
      ;;
    ?)
      echo "*** ? ***"
      usage
      exit 1
      ;;
    :)
      echo "*** : ***"
      usage
      exit 1
      ;;
    esac
  done

  if [[ -z $openshift_host ]]; then
    echo "Missing *REQUIRED* field:"
    echo "  -h <OpenShift Host> *REQUIRED* Openshift Host Name \\"
    echo ""
    usage
    exit 1
  fi

  if [[ -z $openshift_port ]]; then
    echo "Missing *REQUIRED* field:"
    echo "  -p <OpenShift Port> *REQUIRED* Openshift Port Number \\"
    echo ""
    usage
    exit 1
  fi

  if [[ -z $openshift_user ]]; then
    echo "Missing *REQUIRED* field:"
    echo "  -u <OpenShift User> *REQUIRED* Openshift User Name \\"
    echo ""
    usage
    exit 1
  fi

  if [[ -z $project_name ]]; then
    echo "Missing *REQUIRED* field:"
    echo "  -P <Project Name>   *REQUIRED* Openshift Project Name \\"
    echo ""
    usage
    exit 1
  fi

  if [[ $release != "cfme" ]] && [[ $release != "miq" ]]; then
    echo "Invalied value:"
    echo "  -R <release name> must be miq or cfme \\"
    echo ""
    usage
    exit 1
  fi

  echo "openshift_host       ->${openshift_host}<-"
  echo "openshift_port       ->${openshift_port}<-"
  echo "openshift_user       ->${openshift_user}<-"
  echo "project_name         ->${project_name}<-"
  echo "project_description  ->${project_description}<-"
  echo "project_displayname  ->${project_displayname}<-"
  echo "application_domain   ->${application_domain}<-"
  echo "release              ->${release}<-"
  echo "minishift            ->${minishift}<-"
  echo "repo                 ->${repo}<-"
  echo "branch               ->${branch}<-"
  echo "trial_run            ->${trial_run}<-"
}

