#!/usr/bin/env bash

usage() {
  this_script="$(basename $0)"

  # Optional
  echo "Usage: ${this_script} [options]"

  echo "Required switches:"
  echo "  -h <Manager Host> \\"
  echo "  -s <directory server> \\"
  echo "  -d <domain> \\"
  echo "  -r <realm> \\"
  echo "  -u <directory server principal user> \\"
  echo "  -p <directory server principal user password> \\"
  echo "  -a <AD domain> \\"
  echo ""

  echo "Optional switches:"
  echo "  -t [false] trial_run flag \\"
  echo ""

  echo "Example usage:"
  echo "${this_script} \\"
  echo "  -h mgr-pod.example.com \\"
  echo "  -s domain-server.example.com \\"
  echo "  -d example.com \\"
  echo "  -r EXAMPLE.COM \\"
  echo "  -u admin \\"
  echo "  -p secret_password \\"
  echo ""
}

parse_cmg_args() {
  echo -e "\n*** Invoked function ${FUNCNAME} ***"

  trial_run=false
  release="miq"

  while getopts "h:s:d:r:u:p:tR:a:" opt; do
    case $opt in
    h)
      mgr_host=$OPTARG
      ;;
    a)
      domain=$OPTARG
      ;;
    s)
      server=$OPTARG
      ;;
    d)
      domain=$OPTARG
      ;;
    r)
      realm=$OPTARG
      ;;
    u)
      user=$OPTARG
      ;;
    p)
      user_password=$OPTARG
      ;;
    t)
      trial_run=true
      ;;
    R)
      release=$OPTARG
      ;;
    ?)
      echo "*** ? ***"
      usage
      exit 1
      ;;
    :)
      echo "*** : ***"
      usage
      exit 1
      ;;
    esac
  done

  if [ -z $mgr_host ]; then
    usage
    error_exit "${FUNCNAME} Missing *REQUIRED* field: -h <Manager Host>"
  fi

  if [ -z $server ]; then
    usage
    error_exit "${FUNCNAME} Missing -s <directory server>"
  fi

  if [ -z $domain ]; then
    usage
    error_exit "${FUNCNAME} Missing -d <domain>"
  fi

  if [ -z $realm ]; then
    usage
    error_exit "${FUNCNAME} Missing -r <real>"
  fi

  if [ -z $user ]; then
    usage
    error_exit "${FUNCNAME} Missing -u <directory server principal user>"
  fi

  if [ -z $user_password ]; then
    usage
    error_exit "${FUNCNAME} Missing *REQUIRED* field: -p <directory server principal user password>"
  fi

  if [[ $release != "cfme" ]] && [[ $release != "miq" ]]; then
    echo "Invalied value:"
    echo "  -R <release name> must be miq or cfme \\"
    echo ""
    usage
    exit 1
  fi

  echo "mgr_host                ->${mgr_host}<-"
  echo "server                  ->${server}<-"
  echo "domain                  ->${domain}<-"
  echo "realm                   ->${realm}<-"
  echo "user                    ->${user}<-"
  echo "user_password           ->${user_password}<-"
  echo "release                 ->${release}<-"
  echo "trial_run               ->${trial_run}<-"
}

